### ISSUE TITLE
Error executing tests, dependency not indicated

### ISSUE THREAD

**Issue by gustafsilva** [cahilfoley/utils#9]
**Describe the bug**
To run the tests it is necessary to have `yarn` installed.
However this is not indicated in `README.md` and `yarn` is not in the `"devDependencies"` list in `package.json`.

**To Reproduce**
```shell
> yarn type-check && jest

sh: 1: yarn: not found
npm ERR! Test failed.  See above for more details.
```

**Expected behavior**
That all tests run.

**Additional context**
Creating and testing more functions.

**Possible solutions**
* Indicate in the `README.md` that you need to have `yarn` installed.
* Add it to the `devDependencies` list in `package.json`.

I can do that if i have to. :+1:

**Comment by cahilfoley** [comment]
I didn't even think of adding `yarn` to the `devDependencies`, that was a good idea, thanks!
